#!/bin/bash
#
# Pop PHP Framework BASH CLI script (http://www.popphp.org/)
# https://github.com/popphp/popphp2
# http://www.popphp.org/license    New BSD License
#
# Possible arguments
#
# ./pop check             Check the current configuration for required dependencies
# ./pop help              Display this help
# ./pop build file.php    Build an application based on the build file specified
# ./pop show              Show project install instructions
# ./pop version           Display version of Pop PHP Framework
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
CYG_PATH="$( which cygpath 2> /dev/null )"

if [ "$CYG_PATH" != "" ]; then
    SCRIPT_PATH="$( cygpath -w $SCRIPT_DIR )\\pop.php $@"
    SCRIPT_PATH=${SCRIPT_PATH//\\/\/}
else
    SCRIPT_PATH="$SCRIPT_DIR/pop.php $@"
fi
php $SCRIPT_PATH
