name: phpunit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  XDEBUG_MODE: debug,coverage

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3' ]

    steps:
      - uses: actions/checkout@v3

      #- name: Validate composer.json and composer.lock
      #  run: composer validate

      - name: Clear Cache
        run: composer clear-cache

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        run: composer run-script test
